apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: botmusica-pdb
  namespace: botmusica
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: botmusica
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: lavalink-pdb
  namespace: botmusica
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: lavalink
