apiVersion: v1
kind: Secret
metadata:
  name: botmusica-secret
  namespace: botmusica
type: Opaque
stringData:
  DISCORD_TOKEN: "COLOQUE_SEU_TOKEN_AQUI"
  LAVALINK_PASSWORD: "troque_para_senha_forte_16_plus"
  WEB_PANEL_ADMIN_TOKEN: "troque_para_token_forte_32_plus"
  WEB_PANEL_DISCORD_CLIENT_SECRET: "troque_para_oauth_secret"
  WEB_PANEL_SESSION_SECRET: "troque_para_session_secret_32_plus"
  POSTGRES_PASSWORD: "troque_para_senha_forte_16_plus"
  POSTGRES_DSN: "postgresql://botmusica:troque_para_senha_forte_16_plus@postgres:5432/botmusica"
