server:
  port: ${SERVER_PORT:2333}

lavalink:
  server:
    password: ${LAVALINK_SERVER_PASSWORD:youshallnotpass}
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
  plugins:
    - dependency: 'dev.lavalink.youtube:youtube-plugin:${YOUTUBE_PLUGIN_VERSION:1.18.0}'
      snapshot: false
    - dependency: 'com.github.topi314.lavasrc:lavasrc-plugin:${LAVASRC_PLUGIN_VERSION:4.8.1}'
      snapshot: false
    - dependency: 'com.github.topi314.lavasearch:lavasearch-plugin:${LAVASEARCH_PLUGIN_VERSION:1.0.0}'
      snapshot: false
    - dependency: 'com.github.topi314.sponsorblock:sponsorblock-plugin:${SPONSORBLOCK_PLUGIN_VERSION:3.0.1}'
      snapshot: false
    - dependency: 'com.github.topi314.lavalyrics:lavalyrics-plugin:${LAVALYRICS_PLUGIN_VERSION:1.1.0}'
      snapshot: false

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - WEBEMBEDDED
  lavasrc:
    providers:
      - 'ytsearch:"%ISRC%"'
      - 'ytsearch:%QUERY%'
    sources:
      spotify: true
      applemusic: false
      deezer: false
      youtube: true
    spotify:
      clientId: ${SPOTIFY_CLIENT_ID:}
      clientSecret: ${SPOTIFY_CLIENT_SECRET:}
      spDc: ${SPOTIFY_SP_DC:}
      countryCode: ${SPOTIFY_COUNTRY_CODE:US}
      customTokenEndpoint: ${SPOTIFY_CUSTOM_TOKEN_ENDPOINT:}
      preferAnonymousToken: true
      playlistLoadLimit: 1
      albumLoadLimit: 1
      resolveArtistsInSearch: false
